[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=10485760
FileLogger\Path=/config/qBittorrent/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=false
Session\AddTrackersFromURLEnabled=true
Session\AdditionalTrackersURL=https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt
Session\DefaultSavePath=/data/torrents/
Session\Encryption=1
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\ShareLimitAction=Stop
Session\TempPath=/data/torrents/incomplete/

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/data/torrents/
Downloads\TempPath=/data/torrents/incomplete/
General\DeleteTorrentsFilesAsDefault=true
General\Locale=en
WebUI\Address=*
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=false
WebUI\MaxAuthenticationFailCount=300
WebUI\Port=8080
WebUI\SecureCookie=true
WebUI\ServerDomains=*

[RSS]
AutoDownloader\DownloadRepacks=true
