server:
  interface: 0.0.0.0
  interface: ::0
  port: 53
  do-ip4: yes
  do-ip6: yes
  do-udp: yes
  do-tcp: yes
  prefer-ip6: yes
  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  qname-minimisation: yes
  prefetch: yes
  rrset-roundrobin: yes
  use-caps-for-id: no
  edns-buffer-size: 1232
  cache-min-ttl: 300
  cache-max-ttl: 86400
  num-threads: 2
  so-reuseport: yes
  log-time-ascii: yes
  verbosity: 1
  logfile: "/var/log/unbound/unbound.log"
  access-control: 127.0.0.0/8 allow
  access-control: ::1 allow
  access-control: 172.28.0.0/24 allow
  access-control: fd42:4242:4242::/64 allow

remote-control:
  control-enable: no
